using System;
using System.Diagnostics;
using System.IO;
using System.Threading;
using System.Threading.Tasks;

namespace Menace.Modkit.App.Services;

/// <summary>
/// Service for generating Il2CppAssemblies by launching the game with MelonLoader.
/// Il2CppAssemblies are C# proxy assemblies that allow modding IL2CPP games.
/// They're generated by MelonLoader's Il2CppAssemblyGenerator during game startup.
/// </summary>
public class Il2CppGeneratorService
{
    private static readonly Lazy<Il2CppGeneratorService> _instance = new(() => new Il2CppGeneratorService());
    public static Il2CppGeneratorService Instance => _instance.Value;

    private Il2CppGeneratorService() { }

    /// <summary>
    /// Check if the game is an IL2CPP build (vs Mono).
    /// IL2CPP games have GameAssembly.dll instead of managed DLLs.
    /// </summary>
    public bool IsIl2CppGame(string gamePath)
    {
        try
        {
            var gameAssemblyPath = Path.Combine(gamePath, "GameAssembly.dll");
            return File.Exists(gameAssemblyPath);
        }
        catch
        {
            return false;
        }
    }

    /// <summary>
    /// Check if Il2CppAssemblies have already been generated.
    /// </summary>
    public bool AssembliesExist(string gamePath)
    {
        try
        {
            var il2cppDir = Path.Combine(gamePath, "MelonLoader", "Il2CppAssemblies");
            if (!Directory.Exists(il2cppDir))
                return false;

            // Check for critical assemblies
            var criticalAssemblies = new[]
            {
                "Il2Cppmscorlib.dll",
                "Assembly-CSharp.dll",
                "UnityEngine.CoreModule.dll"
            };

            foreach (var dll in criticalAssemblies)
            {
                if (!File.Exists(Path.Combine(il2cppDir, dll)))
                    return false;
            }

            return true;
        }
        catch
        {
            return false;
        }
    }

    /// <summary>
    /// Generate Il2CppAssemblies by launching the game and waiting for generation to complete.
    /// </summary>
    /// <param name="gamePath">Path to game installation</param>
    /// <param name="progress">Progress callback for status updates</param>
    /// <param name="ct">Cancellation token</param>
    /// <returns>True if assemblies were generated successfully</returns>
    public async Task<bool> GenerateAssembliesAsync(
        string gamePath,
        IProgress<string>? progress = null,
        CancellationToken ct = default)
    {
        try
        {
            // Find game executable
            var gameExePath = FindGameExecutable(gamePath);
            if (string.IsNullOrEmpty(gameExePath))
            {
                ModkitLog.Error("[Il2CppGenerator] Could not find game executable");
                progress?.Report("Error: Game executable not found");
                return false;
            }

            ModkitLog.Info($"[Il2CppGenerator] Launching game for IL2CPP assembly generation: {gameExePath}");
            progress?.Report("Launching game to generate code compilation support...");

            var il2cppDir = Path.Combine(gamePath, "MelonLoader", "Il2CppAssemblies");

            // Launch game process
            var psi = new ProcessStartInfo
            {
                FileName = gameExePath,
                WorkingDirectory = gamePath,
                UseShellExecute = false,
                CreateNoWindow = true  // Hide game window
            };

            Process? gameProcess = null;
            try
            {
                gameProcess = Process.Start(psi);
                if (gameProcess == null)
                {
                    ModkitLog.Error("[Il2CppGenerator] Failed to start game process");
                    progress?.Report("Error: Could not launch game");
                    return false;
                }

                ModkitLog.Info($"[Il2CppGenerator] Game process started (PID: {gameProcess.Id})");

                // Poll for Il2CppAssemblies directory creation
                // IL2CPP generation usually takes 10-60 seconds
                var maxWaitTime = TimeSpan.FromMinutes(3);
                var pollInterval = TimeSpan.FromSeconds(1);
                var startTime = DateTime.UtcNow;

                while (DateTime.UtcNow - startTime < maxWaitTime)
                {
                    ct.ThrowIfCancellationRequested();

                    // Check if assemblies have been generated
                    if (Directory.Exists(il2cppDir))
                    {
                        // Wait a bit more to ensure all assemblies are written
                        await Task.Delay(TimeSpan.FromSeconds(3), ct);

                        // Verify critical assemblies exist
                        if (AssembliesExist(gamePath))
                        {
                            ModkitLog.Info("[Il2CppGenerator] IL2CPP assemblies generated successfully");
                            progress?.Report("Code compilation support ready!");
                            return true;
                        }
                    }

                    // Update progress
                    var elapsed = (int)(DateTime.UtcNow - startTime).TotalSeconds;
                    progress?.Report($"Generating assemblies... ({elapsed}s)");

                    await Task.Delay(pollInterval, ct);
                }

                // Timeout
                ModkitLog.Warn("[Il2CppGenerator] Timed out waiting for IL2CPP assemblies");
                progress?.Report("Timeout: IL2CPP generation took too long");
                return false;
            }
            finally
            {
                // Kill game process
                if (gameProcess != null && !gameProcess.HasExited)
                {
                    try
                    {
                        ModkitLog.Info($"[Il2CppGenerator] Killing game process (PID: {gameProcess.Id})");
                        gameProcess.Kill(entireProcessTree: true);
                        gameProcess.WaitForExit(5000);
                    }
                    catch (Exception ex)
                    {
                        ModkitLog.Warn($"[Il2CppGenerator] Failed to kill game process: {ex.Message}");
                    }
                }

                gameProcess?.Dispose();
            }
        }
        catch (OperationCanceledException)
        {
            ModkitLog.Info("[Il2CppGenerator] Generation cancelled by user");
            progress?.Report("Cancelled");
            throw;
        }
        catch (Exception ex)
        {
            ModkitLog.Error($"[Il2CppGenerator] Failed to generate assemblies: {ex.Message}");
            progress?.Report($"Error: {ex.Message}");
            return false;
        }
    }

    /// <summary>
    /// Find the game executable in the game directory.
    /// Looks for .exe files, prioritizing those matching common patterns.
    /// </summary>
    private string? FindGameExecutable(string gamePath)
    {
        try
        {
            var exeFiles = Directory.GetFiles(gamePath, "*.exe");

            if (exeFiles.Length == 0)
                return null;

            // Prefer executables with common game patterns
            var gameName = Path.GetFileName(gamePath);

            foreach (var exe in exeFiles)
            {
                var exeName = Path.GetFileNameWithoutExtension(exe).ToLowerInvariant();

                // Skip known non-game executables
                if (exeName.Contains("unitycrashhandler") ||
                    exeName.Contains("crash") ||
                    exeName.Contains("setup") ||
                    exeName.Contains("launcher"))
                {
                    continue;
                }

                // Prefer executable matching game folder name
                if (exeName == gameName.ToLowerInvariant())
                    return exe;
            }

            // Return first non-excluded .exe
            foreach (var exe in exeFiles)
            {
                var exeName = Path.GetFileNameWithoutExtension(exe).ToLowerInvariant();
                if (!exeName.Contains("unitycrashhandler") &&
                    !exeName.Contains("crash") &&
                    !exeName.Contains("setup") &&
                    !exeName.Contains("launcher"))
                {
                    return exe;
                }
            }

            // Fallback: return first .exe
            return exeFiles.Length > 0 ? exeFiles[0] : null;
        }
        catch (Exception ex)
        {
            ModkitLog.Error($"[Il2CppGenerator] Error finding game executable: {ex.Message}");
            return null;
        }
    }
}
